version: 2
jobs:
  deploy-master:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Deploy Over SSH
          command: |
              ssh $SSH_USER@$SSH_HOST -p $PORT "cd www; git fetch --all; git reset --hard origin/master"
  deploy-drupal:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST -p $PORT "cd dev.theater-oana.be/web/themes/theateroana; git fetch --all; git reset --hard origin/drupal-theme"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-master:
          filters:
            branches:
              only: master
      - deploy-drupal:
          filters:
            branches:
               only: drupal-theme