version: 2
jobs:
  deploy-master:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Deploy Over SSH
          command: |
              ssh $SSH_USER@$SSH_HOST "cd www; git pull"
    branches:
        only: master
  deploy-drupal:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd dev.theater-oana.be; git pull"
    branches:
      only: drupal-theme
workflows:

