version: 2
jobs:
  deploy-master:
    docker:
      - image: circleci/php
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd www; git pull"
  deploy-drupal:
    - image: circleci/php:
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd dev.theater-oana.be; git pull"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-master:
          requires:
            - deploy-master
          filters:
            branches:
              only: master
      - deploy-drupal:
          requires:
            - deplay-drupal
          filters:
            branches:
              only: drupal-site